#cloud-config
packages:
  - python3-pip
  - git
runcmd:
  - export PLAYBOOK_NAME=playbook-kubernetes
  - echo "<ANSIBLE-VAULT-PASS>" >> /root/.ansible-vault-pass
  - sudo pip3 install ansible
  - cd /root/ && sudo git clone https://hcloud-deploy:ud7wRC1XYdGHhi2P5BWP@gitlab.com/jkr.projects/clusters/ansible/playbooks/$PLAYBOOK_NAME.git && sudo git -C $PLAYBOOK_NAME/ checkout release
  - sudo ansible-playbook --vault-password-file /root/.ansible-vault-pass --connection=local --inventory 127.0.0.1, $PLAYBOOK_NAME/main.yml
