---
  - name: "Phase: Deactivate Swap"
    hosts: localhost
    connection: local 
    tasks:
    - name: deactivate swap
      command: swapoff -a
    - name: remove swap-partition from fstab
      command: sed -i '/ swap / s/^/#/' /etc/fstab
      