---
  - name: "Phase: Install essential packages"
    hosts: localhost
    connection: local 
    tasks:
    - name: install packages
      apt:
        pkg:
        - htop
        - vim
        - wget
        - curl
        - mc