---
  - name: "Phase: Setup Kubernetes software"
    hosts: localhost
    connection: local 
    tasks:
    - name: add apt-key for "download.docker.com/linux/ubuntu/"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add apt-key for "packages.cloud.google.com/apt/"
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: add repository "docker"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: add repository "kubernetes"
      apt_repository:
        repo: deb http://packages.cloud.google.com/apt/ kubernetes-xenial main
        state: present
    - name: create directory "kubelet.service.d"
      file:
        path: /etc/systemd/system/kubelet.service.d
        state: directory
    - name: create directory "docker.service.d"
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
    - name: copy 20-hetzner-cloud.conf
      copy:
        src: ../templates/kubernetes/20-hetzner-cloud.conf
        dest: /etc/systemd/system/kubelet.service.d/20-hetzner-cloud.conf
    - name: copy 00-cgroup-systemd.conf
      copy:
        src: ../templates/kubernetes/00-cgroup-systemd.conf
        dest: /etc/systemd/system/docker.service.d/00-cgroup-systemd.conf
    - name: install packages (kubernetes)
      apt:
        pkg:
        - docker-ce=5:19.03.12~3-0~ubuntu-focal
        - kubeadm=1.18.5-00
        - kubectl=1.18.5-00
        - kubelet=1.18.5-00