---
  - name: "Phase: Setup Kubernetes software"
    hosts: localhost
    connection: local 
    tasks:
    - name: create directory kubelet.service.d
      file:
        path: /etc/systemd/system/kubelet.service.d
        state: directory
    - name: create directory docker.service.d
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
    - name: copy 20-hetzner-cloud.conf
      copy:
        src: ../templates/kubernetes/20-hetzner-cloud.conf
        dest: /etc/systemd/system/kubelet.service.d/20-hetzner-cloud.conf
    - name: copy 00-cgroup-systemd.conf
      copy:
        src: ../templates/kubernetes/00-cgroup-systemd.conf
        dest: /etc/systemd/system/docker.service.d/00-cgroup-systemd.conf
    - name: install kubernetes-packages
      apt:
        pkg:
        - docker-ce=1.18.5
        - kubeadm=1.18.5
        - kubectl=1.18.5
        - kubelet=1.18.5
    - name: pull config images
      command: kubeadm config images pull