---
  - name: "Phase: Update System"
    hosts: localhost
    connection: local 
    tasks:
    - name: Update system
      package:
        name: "*"
        update_cache: yes
        state: latest
      register: system_updated
